version: '3'
services:
  app:
    build: .
    ports:
      - "8002:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - ~/.ssh/id_ed25519_anywrite:/usr/src/.ssh/id_ed25519_anywrite
    environment:
      NODE_ENV: development
